// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// UserMiddleware is an autogenerated mock type for the UserMiddleware type
type UserMiddleware struct {
	mock.Mock
}

// OnlyUsers provides a mock function with given fields: next
func (_m *UserMiddleware) OnlyUsers(next echo.HandlerFunc) echo.HandlerFunc {
	ret := _m.Called(next)

	var r0 echo.HandlerFunc
	if rf, ok := ret.Get(0).(func(echo.HandlerFunc) echo.HandlerFunc); ok {
		r0 = rf(next)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.HandlerFunc)
		}
	}

	return r0
}

type mockConstructorTestingTNewUserMiddleware interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserMiddleware creates a new instance of UserMiddleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserMiddleware(t mockConstructorTestingTNewUserMiddleware) *UserMiddleware {
	mock := &UserMiddleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
